### ISSUE TITLE
data is stringified even though data is set to false

### ISSUE THREAD

**Issue by alex-marczinek** [hg-pyun/axios-logger#102]
**Describe the bug**

Set the data config to false : 
`setGlobalConfig({
    data: false,
});`

With version 2.5.0 there was no error thrown when logging requests where the data field contained circular data.
Since version 2.6.0 however the data field will be stringified even though data is set to false:

See 'string-builder.ts':

```
 makeData(data: object) {
      const str = typeof data === `string` ? data : JSON.stringify(data);
      if(this.config.data && data) this.printQueue.push(str);
      return this;
}
```

I would suggest to only stringify the data if this.config.data is true.

**Comment by hg-pyun** [comment]
Thank you for report. I will check and fix. It will be release on 2.6.1 soon.

**Comment by bricka** [comment]
I've just put up a PR to fix this: https://github.com/hg-pyun/axios-logger/pull/114
