### ISSUE TITLE
Option to remove colors

### ISSUE THREAD

**Issue by gzp79** [hg-pyun/axios-logger#141]
I'm using axios-logger to log requests and responses in a test environment (cucumber). It works quite well, but as the log lines are populated in a non-terminal environment (setting the logger option to log into a file) the coloring makes it hard to read the logs.

**Describe the solution you'd like**
It'd be good to have an option to disable coloring. 

Another but more complex solution could be to convert the prefix and similar options to accept a function that returns a string. The default would return some color-escaped text, but clients may configure it as they need. While I think this is a valid option the boilerplate for the configuration could be an issue

**Describe alternatives you've considered**
I could perform some string operation on log lines before sending it to the file but it would be just a hack.

**Comment by hg-pyun** [comment]
I think we can consider that option. As a way to try it, there is a workaround that can be controlled through environmental variables, so would you like to try it?
```
$ FORCE_COLOR=0 ...
````

**Comment by gzp79** [comment]
Thanks but for other reasons i'm not using axious in that project, so according to me  the issue can be closed.
