### ISSUE TITLE
How to log error request body?

### ISSUE THREAD

**Issue by isaachinman** [hg-pyun/axios-logger#142]
We are using `axios-logger` _just_ for error logging in our API, eg:

```ts
instance.interceptors.response.use(res => res, errorLogger)
```

This is working great, however when we receive 4xx responses from some third parties, relevant details are not passed in the error response. The third party might send error/validation content, but not actually reference the entities involved.

Because of this, we want to be able to also log the request body when a 4xx/5xx error is returned.

I haven't been able to work out how this is possible. Any ideas?

**Comment by hg-pyun** [comment]
[binary-gap](https://github.com/hg-pyun/axios-logger#error)

If you want to logging error, pass logging function second argument.

**Comment by isaachinman** [comment]
Thanks @hg-pyun. Not sure if you understood the question.

Regardless, if anyone comes across this issue in the future, here's how it can be done:

```ts
instance.interceptors.response.use(
  res => res,
  error => errorLogger({
    ...error,
    response: {
      ...error.response,
      data: {
        ...error.response.data,
        _request: error.config.data,
      },
    },
  })
)
```
