### ISSUE TITLE
Add response data to errors

### ISSUE THREAD

**Issue by tuckerconnelly** [hg-pyun/axios-logger#16]
Thank you for this library! Could you please add response data to errors? Would help with debugging :)

**Comment by hg-pyun** [comment]
Sure! I will add with options. Thank you feedback.

**Comment by hg-pyun** [comment]
@tuckerconnelly The feature added on 2.0.0! Thank you :D

**Comment by tuckerconnelly** [comment]
Yess, ty :smile: :tada:
