### ISSUE TITLE
Save log data

### ISSUE THREAD

**Issue by hg-pyun** [hg-pyun/axios-logger#20]
## Feature
- Save log data, local file
- Support log-rotate

```js
const config = {
  saveLocal: true,
  logRotate: true,
  filePath: './var/log'
}
```

**Comment by Fylipp** [comment]
Why not allow for custom loggers (akin to #53) instead? A custom logger implementation will require re-writing large parts of logging libraries that already exist without providing any additional benefit. Additionally, the logging can then be seamlessly integrated into existing applications.

**Comment by hg-pyun** [comment]
@Fylipp You're right. I will merge #53
