### ISSUE TITLE
Include headers in logs

### ISSUE THREAD

**Issue by Jonzy3000** [hg-pyun/axios-logger#34]
**Is your feature request related to a problem? Please describe.**
We would like to log request headers (among the HTTP method) for making tests more readable.

**Describe the solution you'd like**
The typings for this behaviour (`RequestLogConfig`) seems to be in place already. We would like the configuration to be respected when printing logs. 

**Additional context**
We think this is the relevant area, where the headers flag should be used.
https://github.com/hg-pyun/axios-logger/blob/master/src/logger/request.ts#L12-L21

Thank you!

**Comment by hg-pyun** [comment]
Thank you for opinion. I'll add it soon!
