### ISSUE TITLE
makeHeader missing from NPM release

### ISSUE THREAD

**Issue by intel352** [hg-pyun/axios-logger#38]
I have axios-logger installed via NPM, v2.2.0. 
Based on github, that release should have makeHeader included: https://github.com/hg-pyun/axios-logger/releases
Which is also backed up by the commit/tag that corresponds with the release: https://github.com/hg-pyun/axios-logger/commit/a6c3fd46a6b4356a94458cfb5a2d34556e17f23d

Yet looking at the code that NPM fetched, makeHeader doesn't exist in the module's lib/ directory.

If I download the 2.2.0 zip asset, I see the same issue, the lib/ directory is outdated. The src/ directory has the latest code, so the assets weren't properly built.

Tagging @hg-pyun

**Comment by intel352** [comment]
Ah, didn't realize the lib/ directory was also committed to Github. I can just point out the missing code directly: https://github.com/hg-pyun/axios-logger/blob/master/lib/common/string-builder.js

No makeHeader

**Comment by intel352** [comment]
I'm trying to build this from the TS source so I can get the missing functionality, but I'm getting a compile error, despite compiling via `npm run build`

```
/axios-logger/src/common/config.ts: Unexpected token, expected ";" (3:16)

  1 | import { ErrorLogConfig, GlobalLogConfig, RequestLogConfig, ResponseLogConfig } from './types';
  2 | 
> 3 | let globalConfig: GlobalLogConfig;
    |                 ^
```

**Comment by hg-pyun** [comment]
Thank you for the report. I'll check it out right away.

**Comment by hg-pyun** [comment]
Hotfixed to version `2.2.1`. From the next time, we will modify it for deployment through the script.
It's weird that it can't be built. If you could fill out a more detailed report, I'll analyze it. For your information, I use tsc Version 3.5.2.
