### ISSUE TITLE
"headers" config is called "header" in readme and on npm

### ISSUE THREAD

**Issue by csciubbach** [hg-pyun/axios-logger#49]
If you do header: true then you do not get headers, because if you look in the code it is looking for headers plural.

Providing the headers option instead of header fixes this.

Documentation needs updating to use plural.

**Comment by hg-pyun** [comment]
Ok I will check it. Thank you for report

**Comment by hg-pyun** [comment]
I start to fix the bug #51.

**Comment by hg-pyun** [comment]
@csciubbach Fixed `2.3.1`. Thank you!
