### ISSUE TITLE
Usage of console.log

### ISSUE THREAD

**Issue by mirfilip** [hg-pyun/axios-logger#53]
This lib looks like a decently thought out thing, apart from hardcoded usage of `console.log`. Is there a reason other general loggers are not allowed?

Majority of people use a real logger like Pino, Bunyan etc.

**Comment by hg-pyun** [comment]
Hi @mirfilip. When I first created this library, I directed zero config. But your idea is good. I will develop it next step!

Thank you :)

**Comment by Fylipp** [comment]
I think this is a great idea. I use [winston](https://github.com/winstonjs/winston) for logging in my Express app and allowing for custom logging implementations would help the request/response logs fit in with the rest of the logging. Maybe `console.log` can be reduced to a fallback logger?

**Comment by hg-pyun** [comment]
@Fylipp I totally agree! We'll develop that feature soon. Thank you very much.

**Comment by filiphoeven** [comment]
Same here. 
Using winston to log to multiple targets like console, log files and syslog.
Looking forward to see the possibilty to add custom logging function. Also for errors.

**Comment by hg-pyun** [comment]
@filiphoeven Thank you for feedback. I wanted to develop it quickly, but I was too busy these days. Now that I have some leeway, add it.

**Comment by KevLehman** [comment]
Hey! Any updates on this? Is there something I can help with? 👍

**Comment by ClintEsteMadera** [comment]
Hi! I came across this library which I find very useful but this is the main reason why I cannot use it. Are you planning to develop this anytime soon? Is there anything I can help with?

**Comment by moltar** [comment]
I think the easiest would be to just expose `printLog` option, which accepts a function that prints the log.
