### ISSUE TITLE
Change logger

### ISSUE THREAD

**Issue by xenoterracide** [hg-pyun/axios-logger#59]
I'd like to be able to log using winston in our app, but I want the output string that you generate. to pass to it.

**Comment by hg-pyun** [comment]
Duplicated #53, I will add soon. T.T

**Comment by ClintEsteMadera** [comment]
if this is a duplicate, kindly suggest closing it...

**Comment by xenoterracide** [comment]
sorry, yes, I forgot about this, looks like a duplicate
