### ISSUE TITLE
Show query params for GET requests

### ISSUE THREAD

**Issue by reslear** [hg-pyun/axios-logger#67]
add query params display for GET requests, and option for controlling.

```ts
await axios.get(`/wp-json/wp/v2/posts`, {
  params: {
    slug: "article",
   _fields: "id"
  }
}
```

![image](https://user-images.githubusercontent.com/12596485/91582133-0cd68280-e958-11ea-8af0-f60ca061f036.png)
to:
![image](https://user-images.githubusercontent.com/12596485/91582531-9e45f480-e958-11ea-9ee2-a3869f2485ef.png)

**Comment by hg-pyun** [comment]
@reslear Thank you for feedback. I will add soon.

**Comment by FezVrasta** [comment]
Adding my request here, I'd love to see the final URL, with the serialized query params, unlike the example posted by the OP.

For example, I'd like to see:

```
[Request] 17:54:56 GET /wp-json/wp-v2-posts/?slug=article&_fields=id
```

so that it's easy to see the final URL hit by Axios.

**Comment by reslear** [comment]
in my case now
<img width="564" alt="Снимок экрана 2020-10-08 в 19 42 32" src="https://user-images.githubusercontent.com/12596485/95488624-7194ec00-099e-11eb-8737-21d79c85ded9.png">

**Comment by FezVrasta** [comment]
The problem with this is that you are not logging what Axios will actually call, the way params are serialized to string may differ by the `qs` options you provided.

**Comment by reslear** [comment]
yes it's true, but this is temporary solution)

**Comment by gurisko** [comment]
I had a look into this one and there doesn't seem to be a consistent way on how to get URL with a query string:
* `AxiosRequestConfig` only contains params object (`AxiosRequestConfig.params`),
* `AxiosResponse` contains `path` (URL with a query string) but it isn't well typed in `axios` itself so I am not sure if we can rely on this (`AxiosResponse.request.path`), it also contains params object (`AxiosResponse.config.params`);
* `AxiosError` same as `AxiosResponse` (`AxiosError.request.path`).

For the consistency I vote to use the params object from `AxiosRequestConfig`.

**Comment by Webbrother** [comment]
Please take a look at this PR: https://github.com/hg-pyun/axios-logger/pull/83

**Comment by hg-pyun** [comment]
It updated on 2.6.0 verison.
