### ISSUE TITLE
logger is a required but not actually used

### ISSUE THREAD

**Issue by xenoterracide** [hg-pyun/axios-logger#71]
logger field is required if config is supplied, but request/responseLogger functions don't actually use it.

I have, e.g. this

```ts
        return responseLogger(request, {
          prefixText: 'Contentful',
          logger: (): void => {},
        });
```
but that logger method is required in the types, but it's not actually used. I'd like for the field to be optional, in case the default is fine. also have printjs use the individual request/response logger settings by default, because in our case we have Contentful which wraps axios, and we have our own axios calls, so having different logger settings would be ideal.

**Comment by hg-pyun** [comment]
Looks good. Do you mean to provide logger as an optician?

**Comment by xenoterracide** [comment]
according to typescript it is an option. Yes, I think it should be an optional option.

**Comment by hg-pyun** [comment]
I understand. The default value of the logger is currently console.log, but the type definition is not optional.

https://github.com/hg-pyun/axios-logger/blob/master/src/common/config.ts#L8
#### As-Is
```ts
let globalConfig: GlobalLogConfig = {
    method: true,
    url: true,
    data: true,
    status: true,
    logger: console.log,
    prefixText: 'Axios',
    dateFormat: false,
    headers: false,
};
```
#### To-Be
```ts
let globalConfig: GlobalLogConfig = {
    method: true,
    url: true,
    data: true,
    status: true,
    logger?: console.log,
    prefixText: 'Axios',
    dateFormat: false,
    headers: false,
};
```
