### ISSUE TITLE
Customizing logger function doesn't work, always uses global config logger

### ISSUE THREAD

**Issue by Iiiggs** [hg-pyun/axios-logger#75]
printLog only knows about global configs:

```
function printLog (text: string) {
    getGlobalConfig().logger(text);
}
```

need to have it merge with provided config overrides

**Comment by gurisko** [comment]
That's a good catch. I opened a PR that should be fixing this. It seems like this deserves a minor release. What are your thoughts @hg-pyun ?

**Comment by hg-pyun** [comment]
@gurisko @liiggs Thank you for catch!, I will review your pull request soon.
