### ISSUE TITLE
2.0.0 Feature Listing

### ISSUE THREAD

**Issue by hg-pyun** [hg-pyun/axios-logger#8]
improve logging features. please comment feature if you have idea.

**Comment by Saberre** [comment]
- [ ] Rewrite code in TypeScript

**Comment by BokDaHoon** [comment]
Logging Level
Insert log to RDBMS & local storage

**Comment by meagar** [comment]
Allow filtering of sensitive attributes. The logs currently contain everything in my request, including the `Authorization` header which causes bearer tokens to be logged, which makes this library unusable for us.

**Comment by hg-pyun** [comment]
@meagar Thank you for advice :D
