### ISSUE TITLE
Error logger crashes if config is null or undefined

### ISSUE THREAD

**Issue by cernadasjuan** [hg-pyun/axios-logger#94]
Hi! Sometimes the axios error comes with config null or undefined, and the errorLogger crashes with this exception

```
ERROR: Cannot destructure property `method` of 'undefined' or 'null'.
```

As a workaround I resolved it by adding this validation in the axios interceptor

```typescript
axiosInstance.interceptors.response.use(responseLogger, (error) => {
  if (error.config && error.response) {
    return errorLogger(error)
  }
  return Promise.reject(error)
})
```

But I think the best solution is to add a validation in the `errorLogger` to prevent this type of crashes (if I catch some free time I can solve this and create the PR).

Thanks!

Note: I think is related with this issue #50

**Comment by hg-pyun** [comment]
Thank you for feedback. I will consider 🙇
